# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

triangle_area = function(v) {
    .Call(`_polygramLCR_triangle_area`, v)
}

rect2bary = function(u, v) {
    .Call(`_polygramLCR_rect2bary`, u, v)
}

hat = function(u, vertex, star) {
    .Call(`_polygramLCR_hat`, u, vertex, star)
}

hat_basis_linear = function(grid, vertex, star) {
    .Call(`_polygramLCR_hat_basis_linear`, grid, vertex, star)
}

