// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// triangle_area
double triangle_area(NumericMatrix v);
RcppExport SEXP _polygramLCR_triangle_area(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(triangle_area(v));
    return rcpp_result_gen;
END_RCPP
}
// rect2bary
NumericVector rect2bary(NumericVector u, NumericMatrix v);
RcppExport SEXP _polygramLCR_rect2bary(SEXP uSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type u(uSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(rect2bary(u, v));
    return rcpp_result_gen;
END_RCPP
}
// hat
double hat(NumericVector u, NumericMatrix vertex, NumericMatrix star);
RcppExport SEXP _polygramLCR_hat(SEXP uSEXP, SEXP vertexSEXP, SEXP starSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type u(uSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type vertex(vertexSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type star(starSEXP);
    rcpp_result_gen = Rcpp::wrap(hat(u, vertex, star));
    return rcpp_result_gen;
END_RCPP
}
// hat_basis_linear
NumericMatrix hat_basis_linear(NumericMatrix grid, NumericMatrix vertex, List star);
RcppExport SEXP _polygramLCR_hat_basis_linear(SEXP gridSEXP, SEXP vertexSEXP, SEXP starSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type vertex(vertexSEXP);
    Rcpp::traits::input_parameter< List >::type star(starSEXP);
    rcpp_result_gen = Rcpp::wrap(hat_basis_linear(grid, vertex, star));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_polygramLCR_triangle_area", (DL_FUNC) &_polygramLCR_triangle_area, 1},
    {"_polygramLCR_rect2bary", (DL_FUNC) &_polygramLCR_rect2bary, 2},
    {"_polygramLCR_hat", (DL_FUNC) &_polygramLCR_hat, 3},
    {"_polygramLCR_hat_basis_linear", (DL_FUNC) &_polygramLCR_hat_basis_linear, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_polygramLCR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
